# Generated by Django 4.2.15 on 2024-08-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=50)),
                ('nom_affichage', models.CharField(max_length=100, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('nationalite', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('adresse_email', models.EmailField(max_length=254, unique=True)),
                ('profil', models.ImageField(blank=True, null=True, upload_to='profil_images/')),
                ('password', models.CharField(max_length=256)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('numero_rue', models.CharField(max_length=50)),
                ('nom_rue', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MembreDirecction',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=50)),
                ('nom_affichage', models.CharField(max_length=100, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('nationalite', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('adresse_email', models.EmailField(max_length=254, unique=True)),
                ('profil', models.ImageField(blank=True, null=True, upload_to='profil_images/')),
                ('password', models.CharField(max_length=256)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('numero_rue', models.CharField(max_length=50)),
                ('nom_rue', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=20)),
                ('tache', models.CharField(choices=[('secretaire', 'Secrétaire'), ('economiste', 'Économiste'), ('prefet', 'Préfet'), ('directeur', 'Directeur'), ('informaticien', 'Informaticien'), ('professeur', 'professeur')], max_length=50)),
                ('niveau_accreditation', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=50)),
                ('nom_affichage', models.CharField(max_length=100, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('nationalite', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('adresse_email', models.EmailField(max_length=254, unique=True)),
                ('profil', models.ImageField(blank=True, null=True, upload_to='profil_images/')),
                ('password', models.CharField(max_length=256)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('numero_rue', models.CharField(max_length=50)),
                ('nom_rue', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=50)),
                ('nom_affichage', models.CharField(max_length=100, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('nationalite', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('adresse_email', models.EmailField(max_length=254, unique=True)),
                ('profil', models.ImageField(blank=True, null=True, upload_to='profil_images/')),
                ('password', models.CharField(max_length=256)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('numero_rue', models.CharField(max_length=50)),
                ('nom_rue', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=20)),
                ('est_enfant', models.BooleanField(default=False)),
                ('enfants', models.ManyToManyField(blank=True, related_name='parents_eleve', to='account_management.eleve')),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='enfants_eleve', to='account_management.parent'),
        ),
    ]
